# Generated by Django 5.2 on 2025-04-14 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image_url', models.ImageField(blank=True, upload_to='media/', verbose_name='URL изображения')),
                ('condition', models.CharField(max_length=50, verbose_name='Состояние товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_category', to='ad.ad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_category', to='ad.category')),
            ],
            options={
                'verbose_name': 'категория объявления',
                'verbose_name_plural': 'Категории объявлений',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(related_name='ad', through='ad.AdCategory', to='ad.category', verbose_name='Категория товара'),
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий к предложению')),
                ('status', models.CharField(choices=[('Waiting', 'Ожидает'), ('Accepted', 'Принята'), ('Declined', 'Отклонена')], default='Waiting', verbose_name='Статус предложения')),
                ('ad_recive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recive', to='ad.ad', verbose_name='Объявление-получатель')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ad.ad', verbose_name='Объявление-инициатор')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.AddConstraint(
            model_name='adcategory',
            constraint=models.UniqueConstraint(fields=('ad', 'category'), name='adcategory_unique'),
        ),
    ]
